export { default as NotFound } from './404';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Send } from './Send';
export { default as Home } from './user/Home';
export { default as Inbox } from './user/Inbox';
export { default as Message } from './user/Message';
export { default as Settings } from './user/Settings';
